// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRSK0BuE7oxbxW5KP11s-V_IsXBA4oLPE',
    appId: '1:837135980487:web:a33b55b9cbad30679e6be2',
    messagingSenderId: '837135980487',
    projectId: 'luarsekolah-dafa',
    authDomain: 'luarsekolah-dafa.firebaseapp.com',
    storageBucket: 'luarsekolah-dafa.firebasestorage.app',
    measurementId: 'G-VKPJKYT0L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCb19NuHZ7lN5Qaf3F1W7ysy6GBNr7fLs',
    appId: '1:837135980487:android:7232a65fb91a60229e6be2',
    messagingSenderId: '837135980487',
    projectId: 'luarsekolah-dafa',
    storageBucket: 'luarsekolah-dafa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpRJT27ZBR8JfOJZdO7w4gg52IP_QdkWM',
    appId: '1:837135980487:ios:d19889d44cd353339e6be2',
    messagingSenderId: '837135980487',
    projectId: 'luarsekolah-dafa',
    storageBucket: 'luarsekolah-dafa.firebasestorage.app',
    iosBundleId: 'com.dafa.luarsekolah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpRJT27ZBR8JfOJZdO7w4gg52IP_QdkWM',
    appId: '1:837135980487:ios:d19889d44cd353339e6be2',
    messagingSenderId: '837135980487',
    projectId: 'luarsekolah-dafa',
    storageBucket: 'luarsekolah-dafa.firebasestorage.app',
    iosBundleId: 'com.dafa.luarsekolah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRSK0BuE7oxbxW5KP11s-V_IsXBA4oLPE',
    appId: '1:837135980487:web:f03cc28c99efc96b9e6be2',
    messagingSenderId: '837135980487',
    projectId: 'luarsekolah-dafa',
    authDomain: 'luarsekolah-dafa.firebaseapp.com',
    storageBucket: 'luarsekolah-dafa.firebasestorage.app',
    measurementId: 'G-B7R9W6FJL6',
  );
}
